name: Deploy Side Project

on:
  push:
    branches:
      - main  # Run this workflow when pushing to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Adjust Node.js version if needed

    - name: Install Dependencies
      run: npm install

    - name: Build Project
      run: npm run build  # Replace with your project's build command if applicable
